# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests and save results
      run: |
        mkdir -p test-results
        python -m unittest discover -s tests > test-results/results.txt

    - name: Append test results to docs
      run: |
        echo "\n## Test Results\n" >> docs.md
        cat test-results/results.txt >> docs.md

    - name: Upload updated docs.md
      uses: actions/upload-artifact@v2
      with:
        name: updated-docs
        path: docs.md
