name: Python application

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: sagemath-env
          environment-file: environment.yml

      - name: List files in root directory
        run: ls -l

      - name: Set up conda environment and install dependencies
        run: |
          conda env create -f environment.yml
          conda activate sagemath-env

      - name: Install Python dependencies
        run: |
          conda activate sagemath-env
          pip install --upgrade pip setuptools wheel Cython
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: |
          conda activate sagemath-env
          python -m pytest --import-mode=append tests/
