# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: develop
  pull_request:
    branches: develop

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: List files in root directory
      run: ls -l
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmpc-dev libfplll-dev libgmp-dev libmpfr-dev
    - name: Set up virtual environment
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip setuptools wheel Cython

    - name: Install Python dependencies
      run: |
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        pip install --upgrade pip 
        pip install flake8 pytest
        pip install --upgrade setuptools wheel twine
        pip install --upgrade Cython
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
- name: Run unit tests
        run: python -m pytest --import-mode=append tests/